import type { WizardState, AppDefinition, AppConfig } from '../types';
import { getAppByIdWithCustom } from '../utils/appLookup';
import { getActiveConnections, type AppConnection } from '../data/connections';

function resolveContainerName(app: AppDefinition, config?: AppConfig): string {
  return config?.containerName || app.id;
}

// Which connection types we can auto-configure
const AUTO_TYPES = new Set(['download-client', 'indexer']);

// API versions per *arr app for download client endpoints
const DOWNLOAD_CLIENT_API: Record<string, string> = {
  sonarr: '/api/v3/downloadclient',
  radarr: '/api/v3/downloadclient',
  luminarr: '/api/v3/downloadclient',
  lidarr: '/api/v1/downloadclient',
};

// Prowlarr app sync: implementation + configContract per target
const PROWLARR_APP_MAP: Record<string, { impl: string; contract: string; categories: number[] }> = {
  sonarr: { impl: 'Sonarr', contract: 'SonarrSettings', categories: [5000, 5010, 5020, 5030, 5040, 5045, 5050, 5090] },
  radarr: { impl: 'Radarr', contract: 'RadarrSettings', categories: [2000, 2010, 2020, 2030, 2040, 2045, 2050, 2060] },
  luminarr: { impl: 'Radarr', contract: 'RadarrSettings', categories: [2000, 2010, 2020, 2030, 2040, 2045, 2050, 2060] },
  lidarr: { impl: 'Lidarr', contract: 'LidarrSettings', categories: [3000, 3010, 3020, 3030, 3040] },
};

// Download client implementations
const DL_CLIENT_MAP: Record<string, { impl: string; contract: string; port: number; defaultPassword?: string }> = {
  qbittorrent: { impl: 'QBittorrent', contract: 'QBittorrentSettings', port: 8080 },
  transmission: { impl: 'Transmission', contract: 'TransmissionSettings', port: 9091 },
  deluge: { impl: 'Deluge', contract: 'DelugeSettings', port: 8112, defaultPassword: 'deluge' },
};

// Download category per *arr app (TRaSH Guides convention)
const DL_CATEGORY: Record<string, string> = {
  sonarr: 'tv-sonarr',
  radarr: 'radarr',
  luminarr: 'radarr',
  lidarr: 'lidarr',
};

/** Returns the list of auto-configurable connections for the given app selection. */
export function getAutoConfigConnections(selectedApps: string[]): AppConnection[] {
  return getActiveConnections(selectedApps).filter((c) => {
    if (!AUTO_TYPES.has(c.type)) return false;
    // Download clients require auth credentials we can't reliably obtain
    if (c.type === 'download-client') return false;
    // Indexer connections: Prowlarr → *arr apps or Prowlarr → FlareSolverr
    if (c.type === 'indexer') {
      if (c.from !== 'prowlarr') return false;
      return c.to in PROWLARR_APP_MAP || c.to === 'flaresolverr';
    }
    return false;
  });
}

export function generateConfigureScript(state: WizardState): string {
  const conns = getAutoConfigConnections(state.selectedApps);
  if (conns.length === 0) return '';

  const resolve = (appId: string): string => {
    const app = getAppByIdWithCustom(appId, state.customApps);
    return app ? resolveContainerName(app, state.appConfigs[appId]) : appId;
  };

  const getPort = (appId: string): number => {
    const app = getAppByIdWithCustom(appId, state.customApps);
    return app?.ports[0]?.container || 0;
  };

  const lines: string[] = [];

  // ── Shebang + header ──
  lines.push('#!/bin/sh');
  lines.push('# Auto-generated by ArrForge — configures connections between services');
  lines.push('');

  // ── Utility functions ──
  lines.push('log() { printf "[configure] %s\\n" "$1"; }');
  lines.push('');
  lines.push('get_api_key() {');
  lines.push('  config="/config/$1/config.xml"');
  lines.push('  i=0');
  lines.push('  while [ "$i" -lt 30 ]; do');
  lines.push('    if [ -f "$config" ]; then');
  lines.push('      key=$(sed -n \'s/.*<ApiKey>\\([^<]*\\)<\\/ApiKey>.*/\\1/p\' "$config")');
  lines.push('      if [ -n "$key" ]; then echo "$key"; return 0; fi');
  lines.push('    fi');
  lines.push('    i=$((i + 1)); sleep 2');
  lines.push('  done');
  lines.push('  log "ERROR: Could not read API key for $1 after 60s"');
  lines.push('  return 1');
  lines.push('}');
  lines.push('');
  lines.push('exists_by_name() {');
  lines.push('  url="$1"; api_key="$2"; name="$3"');
  lines.push('  response=$(curl -sf -H "X-Api-Key: ${api_key}" "$url" 2>/dev/null || echo "[]")');
  lines.push('  echo "$response" | grep -q "\\"name\\".*\\"${name}\\""');
  lines.push('}');
  lines.push('');

  // ── Determine which apps need API keys ──
  const appsNeedingKeys = new Set<string>();
  for (const conn of conns) {
    if (conn.type === 'indexer' && conn.from === 'prowlarr') {
      appsNeedingKeys.add('prowlarr');
      if (conn.to !== 'flaresolverr') appsNeedingKeys.add(conn.to);
    }
    if (conn.type === 'download-client') {
      appsNeedingKeys.add(conn.from);
    }
  }

  // ── Extract API keys ──
  lines.push('# ── Extract API keys ──');
  lines.push('log "Extracting API keys..."');
  for (const appId of appsNeedingKeys) {
    const container = resolve(appId);
    const varName = appId.toUpperCase().replace(/-/g, '_') + '_KEY';
    lines.push(`${varName}=$(get_api_key "${container}") || log "WARN: failed to get API key for ${container}"`);
  }
  lines.push('log "API keys extracted"');
  lines.push('');

  // ── Group connections by type ──
  const indexerConns = conns.filter((c) => c.type === 'indexer');
  const dlConns = conns.filter((c) => c.type === 'download-client');

  // ── Prowlarr → FlareSolverr (indexer proxy) ──
  const flaresolverrConn = indexerConns.find((c) => c.to === 'flaresolverr');
  if (flaresolverrConn) {
    const prowlarrContainer = resolve('prowlarr');
    const prowlarrPort = getPort('prowlarr');
    const fsContainer = resolve('flaresolverr');
    const fsPort = getPort('flaresolverr');
    const prowlarrKey = 'PROWLARR_KEY';

    lines.push('# ── Prowlarr: Add FlareSolverr as indexer proxy ──');
    lines.push('log "Prowlarr: adding FlareSolverr indexer proxy..."');
    lines.push(`if exists_by_name "http://${prowlarrContainer}:${prowlarrPort}/api/v1/indexerProxy" "\${${prowlarrKey}}" "FlareSolverr"; then`);
    lines.push('  log "  already exists, skipping"');
    lines.push('else');
    lines.push(`  curl -sf -X POST "http://${prowlarrContainer}:${prowlarrPort}/api/v1/indexerProxy" \\`);
    lines.push(`    -H "X-Api-Key: \${${prowlarrKey}}" \\`);
    lines.push(`    -H "Content-Type: application/json" \\`);
    lines.push(`    -d '{"name":"FlareSolverr","implementation":"FlareSolverr","configContract":"FlareSolverrSettings","fields":[{"name":"host","value":"http://${fsContainer}:${fsPort}"},{"name":"requestTimeout","value":60}],"tags":[]}' > /dev/null`);
    lines.push('  log "  done"');
    lines.push('fi');
    lines.push('');

  }

  // ── Prowlarr → *arr apps (app sync) ──
  const appSyncConns = indexerConns.filter((c) => c.to !== 'flaresolverr');
  for (const conn of appSyncConns) {
    const mapping = PROWLARR_APP_MAP[conn.to];
    if (!mapping) continue;

    const prowlarrContainer = resolve('prowlarr');
    const prowlarrPort = getPort('prowlarr');
    const targetContainer = resolve(conn.to);
    const targetPort = getPort(conn.to);
    const prowlarrKey = 'PROWLARR_KEY';
    const targetKey = conn.to.toUpperCase().replace(/-/g, '_') + '_KEY';
    const displayName = mapping.impl === 'Radarr' && conn.to === 'luminarr' ? 'Luminarr' : mapping.impl;
    const categories = JSON.stringify(mapping.categories);

    lines.push(`# ── Prowlarr: Add ${displayName} app sync ──`);
    lines.push(`log "Prowlarr: adding ${displayName} app sync..."`);
    lines.push(`if exists_by_name "http://${prowlarrContainer}:${prowlarrPort}/api/v1/applications" "\${${prowlarrKey}}" "${displayName}"; then`);
    lines.push('  log "  already exists, skipping"');
    lines.push('else');
    lines.push(`  curl -sf -X POST "http://${prowlarrContainer}:${prowlarrPort}/api/v1/applications" \\`);
    lines.push(`    -H "X-Api-Key: \${${prowlarrKey}}" \\`);
    lines.push(`    -H "Content-Type: application/json" \\`);
    lines.push(`    -d "{\\"syncLevel\\":\\"fullSync\\",\\"name\\":\\"${displayName}\\",\\"implementation\\":\\"${mapping.impl}\\",\\"configContract\\":\\"${mapping.contract}\\",\\"fields\\":[{\\"name\\":\\"prowlarrUrl\\",\\"value\\":\\"http://${prowlarrContainer}:${prowlarrPort}\\"},{\\"name\\":\\"baseUrl\\",\\"value\\":\\"http://${targetContainer}:${targetPort}\\"},{\\"name\\":\\"apiKey\\",\\"value\\":\\"\${${targetKey}}\\"},{\\"name\\":\\"syncCategories\\",\\"value\\":${categories}}],\\"tags\\":[]}" > /dev/null`);
    lines.push('  log "  done"');
    lines.push('fi');
    lines.push('');

  }

  // ── *arr → download clients ──
  for (const conn of dlConns) {
    const dlMapping = DL_CLIENT_MAP[conn.to];
    if (!dlMapping) continue;
    const apiPath = DOWNLOAD_CLIENT_API[conn.from];
    if (!apiPath) continue;

    const arrContainer = resolve(conn.from);
    const arrPort = getPort(conn.from);
    const dlContainer = resolve(conn.to);
    const arrKey = conn.from.toUpperCase().replace(/-/g, '_') + '_KEY';
    const category = DL_CATEGORY[conn.from] || conn.from;
    const displayName = dlMapping.impl;
    const arrDisplayName = getAppByIdWithCustom(conn.from, state.customApps)?.name || conn.from;

    // Build fields array for the download client
    const fields: string[] = [];
    fields.push(`{\\"name\\":\\"host\\",\\"value\\":\\"${dlContainer}\\"}`);
    fields.push(`{\\"name\\":\\"port\\",\\"value\\":${dlMapping.port}}`);

    if (conn.to === 'qbittorrent') {
      // No auth needed — subnet whitelist handles it
      fields.push(`{\\"name\\":\\"tvCategory\\",\\"value\\":\\"${category}\\"}`);
      fields.push(`{\\"name\\":\\"movieCategory\\",\\"value\\":\\"${category}\\"}`);
      fields.push(`{\\"name\\":\\"musicCategory\\",\\"value\\":\\"${category}\\"}`);
    } else if (conn.to === 'transmission') {
      fields.push(`{\\"name\\":\\"username\\",\\"value\\":\\"admin\\"}`);
      fields.push(`{\\"name\\":\\"password\\",\\"value\\":\\"transmission\\"}`);
      fields.push(`{\\"name\\":\\"tvCategory\\",\\"value\\":\\"${category}\\"}`);
      fields.push(`{\\"name\\":\\"movieCategory\\",\\"value\\":\\"${category}\\"}`);
      fields.push(`{\\"name\\":\\"musicCategory\\",\\"value\\":\\"${category}\\"}`);
    } else if (conn.to === 'deluge') {
      fields.push(`{\\"name\\":\\"password\\",\\"value\\":\\"${dlMapping.defaultPassword}\\"}`);
      fields.push(`{\\"name\\":\\"tvCategory\\",\\"value\\":\\"${category}\\"}`);
      fields.push(`{\\"name\\":\\"movieCategory\\",\\"value\\":\\"${category}\\"}`);
      fields.push(`{\\"name\\":\\"musicCategory\\",\\"value\\":\\"${category}\\"}`);
    }

    const protocol = (conn.to === 'sabnzbd' || conn.to === 'nzbget') ? 'usenet' : 'torrent';
    const fieldsJson = `[${fields.join(',')}]`;

    lines.push(`# ── ${arrDisplayName}: Add ${displayName} download client ──`);
    lines.push(`log "${arrDisplayName}: adding ${displayName} download client..."`);
    lines.push(`if exists_by_name "http://${arrContainer}:${arrPort}${apiPath}" "\${${arrKey}}" "${displayName}"; then`);
    lines.push('  log "  already exists, skipping"');
    lines.push('else');
    lines.push(`  curl -sf -X POST "http://${arrContainer}:${arrPort}${apiPath}" \\`);
    lines.push(`    -H "X-Api-Key: \${${arrKey}}" \\`);
    lines.push(`    -H "Content-Type: application/json" \\`);
    lines.push(`    -d "{\\"enable\\":true,\\"name\\":\\"${displayName}\\",\\"implementation\\":\\"${dlMapping.impl}\\",\\"configContract\\":\\"${dlMapping.contract}\\",\\"protocol\\":\\"${protocol}\\",\\"fields\\":${fieldsJson}}" > /dev/null`);
    lines.push('  log "  done"');
    lines.push('fi');
    lines.push('');

  }

  lines.push('log "Auto-configure complete!"');
  lines.push('');

  return lines.join('\n');
}
