import type { WizardState } from '../types';
import { getAppById } from '../data/apps';

export function generateReadme(state: WizardState): string {
  const lines: string[] = [];

  lines.push('# Media Server Stack');
  lines.push('');
  lines.push('Generated by [ArrForge](https://github.com/arrforge/arrforge)');
  lines.push('');

  // Quick start
  lines.push('## Quick Start');
  lines.push('');
  lines.push('```bash');
  lines.push('# Start all services');
  lines.push('docker compose up -d');
  lines.push('');
  lines.push('# View logs');
  lines.push('docker compose logs -f');
  lines.push('');
  lines.push('# Stop all services');
  lines.push('docker compose down');
  lines.push('```');
  lines.push('');

  // Service URLs
  lines.push('## Service URLs');
  lines.push('');
  lines.push('| Service | URL | Notes |');
  lines.push('|---------|-----|-------|');

  for (const appId of state.selectedApps) {
    const app = getAppById(appId);
    if (!app) continue;
    if (app.ports.length === 0) {
      lines.push(`| ${app.name} | N/A | ${app.notes || 'No web UI'} |`);
      continue;
    }
    const port = app.ports[0];
    const url = app.networkMode === 'host'
      ? `http://YOUR_IP:${port.host}`
      : `http://localhost:${port.host}`;
    lines.push(`| ${app.name} | ${url} | ${port.description} |`);
  }
  lines.push('');

  // Folder structure
  lines.push('## Folder Structure');
  lines.push('');
  lines.push('This setup uses the [TRaSH Guides recommended folder structure](https://trash-guides.info/Hardlinks/How-to-setup-for/Docker/):');
  lines.push('');
  lines.push('```');
  lines.push(`${state.basePath}/`);
  lines.push(`├── torrents/       # Torrent downloads`);
  lines.push(`├── usenet/         # Usenet downloads`);
  lines.push(`├── media/`);
  lines.push(`│   ├── movies/     # Movie library`);
  lines.push(`│   ├── tv/         # TV show library`);
  lines.push(`│   ├── music/      # Music library`);
  lines.push(`│   └── books/      # Book library`);
  lines.push(`└── config/         # App configs (auto-created)`);
  lines.push('```');
  lines.push('');
  lines.push('This structure enables **hardlinks** and **atomic moves**, which means:');
  lines.push('- No extra disk space used when files are "moved" from downloads to library');
  lines.push('- Instant file moves instead of slow copy + delete operations');
  lines.push('');

  // Create directories
  lines.push('### Create the directory structure');
  lines.push('');
  lines.push('```bash');
  lines.push(`mkdir -p ${state.basePath}/{torrents,usenet,media/{movies,tv,music,books},config}`);
  lines.push('```');
  lines.push('');

  // PUID/PGID
  lines.push('## PUID and PGID');
  lines.push('');
  lines.push(`Your setup uses PUID=\`${state.puid}\` and PGID=\`${state.pgid}\`.`);
  lines.push('');
  lines.push('These values ensure containers create files with the correct ownership.');
  lines.push('To find your user\'s IDs, run:');
  lines.push('');
  lines.push('```bash');
  lines.push('id $USER');
  lines.push('```');
  lines.push('');
  lines.push('Update the values in `.env` if they don\'t match.');
  lines.push('');

  // Next steps
  lines.push('## Next Steps');
  lines.push('');
  lines.push('1. Create the folder structure above');
  lines.push('2. Run `docker compose up -d`');
  lines.push('3. Access each service via the URLs above');
  lines.push('4. Configure Prowlarr with your indexers');
  lines.push('5. Connect Sonarr/Radarr to Prowlarr and your download client');
  lines.push('6. Add your media library paths in your media server');
  lines.push('');
  lines.push('For detailed setup guides, see [TRaSH Guides](https://trash-guides.info/).');
  lines.push('');

  return lines.join('\n');
}
