import type { WizardState } from '../types';
import { getAppByIdWithCustom } from '../utils/appLookup';
import { getActiveConnections } from '../data/connections';
import { generateFolderGuide } from './folders';

export function generateReadme(state: WizardState): string {
  const lines: string[] = [];

  lines.push('# Media Server Stack');
  lines.push('');
  lines.push('Generated by [ArrForge](https://github.com/arrforge/arrforge)');
  lines.push('');

  // Quick start
  lines.push('## Quick Start');
  lines.push('');
  lines.push('```bash');
  lines.push('# Start all services');
  lines.push('docker compose up -d');
  lines.push('');
  lines.push('# View logs');
  lines.push('docker compose logs -f');
  lines.push('');
  lines.push('# Stop all services');
  lines.push('docker compose down');
  lines.push('```');
  lines.push('');

  // Service URLs
  lines.push('## Service URLs');
  lines.push('');
  lines.push('| Service | URL | Notes |');
  lines.push('|---------|-----|-------|');

  for (const appId of state.selectedApps) {
    const app = getAppByIdWithCustom(appId, state.customApps);
    if (!app) continue;
    if (app.ports.length === 0) {
      lines.push(`| ${app.name} | N/A | ${app.notes || 'No web UI'} |`);
      continue;
    }
    const port = app.ports[0];
    const url = app.networkMode === 'host'
      ? `http://YOUR_IP:${port.host}`
      : `http://localhost:${port.host}`;
    lines.push(`| ${app.name} | ${url} | ${port.description} |`);
  }
  lines.push('');

  // Folder structure (generated dynamically based on selected apps)
  lines.push(generateFolderGuide(state));
  lines.push('');

  // PUID/PGID
  lines.push('## PUID and PGID');
  lines.push('');
  lines.push(`Your setup uses PUID=\`${state.puid}\` and PGID=\`${state.pgid}\`.`);
  lines.push('');
  lines.push('These values ensure containers create files with the correct ownership.');
  lines.push('To find your user\'s IDs, run:');
  lines.push('');
  lines.push('```bash');
  lines.push('id $USER');
  lines.push('```');
  lines.push('');
  lines.push('Update the values in `.env` if they don\'t match.');
  lines.push('');

  // Connection setup guide
  const activeConns = getActiveConnections(state.selectedApps);
  if (activeConns.length > 0) {
    lines.push('## Connect Your Apps');
    lines.push('');
    lines.push('Your selected apps can be connected to work together. Follow these steps in order:');
    lines.push('');

    // Group by "from" app
    const grouped = new Map<string, typeof activeConns>();
    for (const conn of activeConns) {
      const existing = grouped.get(conn.from) || [];
      existing.push(conn);
      grouped.set(conn.from, existing);
    }

    let stepNum = 1;
    for (const [fromId, conns] of grouped) {
      const fromApp = getAppByIdWithCustom(fromId, state.customApps);
      if (!fromApp) continue;
      for (const conn of conns) {
        const toApp = getAppByIdWithCustom(conn.to, state.customApps);
        if (!toApp) continue;
        lines.push(`${stepNum}. **${fromApp.name} → ${toApp.name}** (${conn.label})`);
        lines.push(`   ${conn.setupInstructions}`);
        lines.push('');
        stepNum++;
      }
    }
  }

  // Next steps
  lines.push('## Next Steps');
  lines.push('');
  lines.push('1. Create the folder structure above');
  lines.push('2. Run `docker compose up -d`');
  lines.push('3. Access each service via the URLs above');
  if (activeConns.length > 0) {
    lines.push('4. Follow the "Connect Your Apps" guide above');
  }
  lines.push('');
  lines.push('For detailed setup guides, see [TRaSH Guides](https://trash-guides.info/).');
  lines.push('');

  return lines.join('\n');
}
