import type { WizardState } from '../types';
import { getAppByIdWithCustom } from '../utils/appLookup';
import { getActiveConnections } from '../data/connections';
import { getAutoConfigConnections } from './configure';
import { hasBeaconApps } from './compose';
import { generateFolderGuide } from './folders';

export function generateReadme(state: WizardState): string {
  const lines: string[] = [];

  lines.push('# Media Server Stack');
  lines.push('');
  lines.push('Generated by [ArrForge](https://github.com/arrforge/arrforge)');
  lines.push('');

  // Quick start
  lines.push('## Quick Start');
  lines.push('');
  lines.push('```bash');
  lines.push('docker compose up -d');
  lines.push('```');
  lines.push('');
  lines.push('That\'s it. The stack handles directory creation, app connections, and download');
  lines.push('client setup automatically on first run.');
  lines.push('');

  // Beacon Stack callout — the generated compose uses weak default passwords
  // (pulse/pulse, etc.) baked into init-db.sql. The official deploy repo
  // rotates these automatically via an init-secrets sidecar.
  if (hasBeaconApps(state.selectedApps)) {
    lines.push('> **Using the Beacon Stack in production?** This wizard output uses simple');
    lines.push('> default passwords for the Postgres users (`pulse/pulse`, `pilot/pilot`, etc.)');
    lines.push('> baked into `init-db.sql`. For a turnkey install with per-run rotated secrets');
    lines.push('> generated inside a Docker volume, clone [beacon-stack/deploy](https://github.com/beacon-stack/deploy)');
    lines.push('> instead. Same stack, stronger defaults.');
    lines.push('');
  }

  lines.push('```bash');
  lines.push('# View logs');
  lines.push('docker compose logs -f');
  lines.push('');
  lines.push('# Check auto-configure results');
  lines.push('docker compose logs auto-configure');
  lines.push('');
  lines.push('# Stop all services');
  lines.push('docker compose down');
  lines.push('```');
  lines.push('');

  // What's automated
  const autoConns = getAutoConfigConnections(state.selectedApps);
  if (autoConns.length > 0) {
    lines.push('## What\'s Auto-Configured');
    lines.push('');
    lines.push('The `auto-configure` service runs once on first startup and sets up:');
    lines.push('');

    const indexerConns = autoConns.filter((c) => c.type === 'indexer' && c.to !== 'flaresolverr');
    const proxyConns = autoConns.filter((c) => c.to === 'flaresolverr');
    const dlConns = autoConns.filter((c) => c.type === 'download-client');

    if (proxyConns.length > 0) {
      lines.push('- **FlareSolverr** as indexer proxy in Prowlarr');
    }
    for (const conn of indexerConns) {
      const toApp = getAppByIdWithCustom(conn.to, state.customApps);
      if (toApp) {
        lines.push(`- **${toApp.name}** synced in Prowlarr (indexer app sync)`);
      }
    }
    for (const conn of dlConns) {
      const fromApp = getAppByIdWithCustom(conn.from, state.customApps);
      const toApp = getAppByIdWithCustom(conn.to, state.customApps);
      if (fromApp && toApp) {
        lines.push(`- **${toApp.name}** as download client in ${fromApp.name}`);
      }
    }
    lines.push('');
    lines.push('If auto-configure fails (e.g. an app was slow to start), re-run it:');
    lines.push('');
    lines.push('```bash');
    lines.push('docker compose restart auto-configure');
    lines.push('```');
    lines.push('');
  }

  // Service URLs
  lines.push('## Service URLs');
  lines.push('');
  lines.push('| Service | URL | Notes |');
  lines.push('|---------|-----|-------|');

  for (const appId of state.selectedApps) {
    const app = getAppByIdWithCustom(appId, state.customApps);
    if (!app) continue;
    if (app.ports.length === 0) {
      lines.push(`| ${app.name} | N/A | ${app.notes || 'No web UI'} |`);
      continue;
    }
    const port = app.ports[0];
    const url = app.networkMode === 'host'
      ? `http://YOUR_IP:${port.host}`
      : `http://localhost:${port.host}`;
    lines.push(`| ${app.name} | ${url} | ${port.description} |`);
  }
  lines.push('');

  // First run auth note
  const arrApps = state.selectedApps.filter((id) => ['sonarr', 'radarr', 'lidarr'].includes(id));
  if (arrApps.length > 0) {
    lines.push('> **First run:** Sonarr, Radarr, and Lidarr require you to create a username');
    lines.push('> and password on first visit. This is enforced by the apps and cannot be skipped.');
    lines.push('');
  }

  // Folder structure
  lines.push(generateFolderGuide(state));
  lines.push('');

  // PUID/PGID
  lines.push('## PUID and PGID');
  lines.push('');
  lines.push(`Your setup uses PUID=\`${state.puid}\` and PGID=\`${state.pgid}\`.`);
  lines.push('');
  lines.push('These values ensure containers create files with the correct ownership.');
  lines.push('To find your user\'s IDs, run:');
  lines.push('');
  lines.push('```bash');
  lines.push('id $USER');
  lines.push('```');
  lines.push('');
  lines.push('Update the values in `.env` if they don\'t match.');
  lines.push('');

  // Manual connection steps (only non-auto-configured connections)
  const allConns = getActiveConnections(state.selectedApps);
  const autoSet = new Set(autoConns.map((c) => `${c.from}-${c.to}`));
  const manualConns = allConns.filter((c) => !autoSet.has(`${c.from}-${c.to}`));

  if (manualConns.length > 0) {
    lines.push('## Manual Setup');
    lines.push('');
    lines.push('These connections need to be configured manually in the app UIs:');
    lines.push('');

    let stepNum = 1;
    for (const conn of manualConns) {
      const fromApp = getAppByIdWithCustom(conn.from, state.customApps);
      const toApp = getAppByIdWithCustom(conn.to, state.customApps);
      if (!fromApp || !toApp) continue;
      lines.push(`${stepNum}. **${fromApp.name} → ${toApp.name}** (${conn.label})`);
      lines.push(`   ${conn.setupInstructions}`);
      lines.push('');
      stepNum++;
    }
  }

  // Next steps
  lines.push('## Next Steps');
  lines.push('');
  lines.push('1. Run `docker compose up -d`');
  lines.push('2. Set up authentication in Sonarr/Radarr on first visit');
  if (state.selectedApps.includes('prowlarr')) {
    lines.push('3. Add indexers in Prowlarr (Settings > Indexers > +)');
  }
  if (manualConns.length > 0) {
    lines.push(`${state.selectedApps.includes('prowlarr') ? '4' : '3'}. Follow the "Manual Setup" section above for remaining connections`);
  }
  lines.push('');
  lines.push('For detailed setup guides, see [TRaSH Guides](https://trash-guides.info/).');
  lines.push('');

  return lines.join('\n');
}
